services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=faq'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=faqusr'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - "5432:5432"
