@conversation=first-conversation
@question="Angeblich habe ich einen ungültiger API-Schlüssel. Was kann ich dagegen tun?"
### Ask a question
GET http://localhost:8080/{{conversation}}/faq?question={{question}}